#去申请 https://mp.weixin.qq.com/debug/cgi-bin/sandbox?t=sandbox/login
wx:
  config:
    appId: "wx71cd4b7e1d5d4925"
    appSecret: "6a74395ba52d02630561031c50c53b0b"
    #模板Id
    templateId: "_q72VbQPIWQ7BCoQ6fKrLNL_y_AjI5ovBIvxM4G517Q"
    openidList:
      - "oHely6JQRDrQf5EAKkpuuGjY2xKU"
      - "oHely6NR5uJRyH4ugY9pumex8Q8Y"

message:
  config:
    birthday1: "11-20" #生日日期
    birthday2: "08-31"
    togetherDate: "2021-04-23" #填你们在一起的那天日期
    message: "Have a happy day and love you"

#去申请 https://tianqiapi.com/user/login
weather:
  config:
    appid: "85348823"
    appSecret: "Rw8IPu8O"
    city: "广州"
#注册并购买第二档次，有券，直接白嫖 https://www.apispace.com/eolink/api/myjj/introduction
ApiSpace:
  enableDaily: true #【新增功能】  true：开启每日一句，false：则不开启
  token: "5cc26sj7p4rosgf7ckb2wnusb1t21tl0"

server:
  port: 8081

